[package]
name = "stm32f4xx"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
cortexm4 = { path = "../../arch/cortex-m4" }
enum_primitive = { path = "../../libraries/enum_primitive" }
kernel = { path = "../../kernel" }

[features]
default = []

stm32f401 = []
stm32f412 = []
stm32f429 = []
stm32f446 = []
