[package]
name = "litex-register-gen"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
description = "Procedural macros for LiteX Tock register abstractions"
homepage = "https://www.tockos.org/"
repository = "https://github.com/tock/tock/tree/master/libraries/litex-register-gen"
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.24"
quote = "1.0.7"
syn = { version = "1.0.48", features = [ "full" ] }
