[package]
name = "nrf51dk"
version = "0.1.0"
authors = ["Amit Levy <amit@amitlevy.com>", "Philip Levis <pal@cs.stanford.edu>"]

[profile.dev]
panic = "abort"
lto = true

[profile.release]
panic = "abort"
lto = true

[dependencies]
rust-libcore = "*"
cortexm0 = { path = "../../arch/cortex-m0" }
capsules = { path = "../../capsules" }
kernel = { path = "../../kernel" }
nrf51 = { path = "../../chips/nrf51" }
