[package]
name = "drivers"
version = "0.1.0"
authors = ["Amit Levy <amit@amitlevy.com>"]

[dependencies]
core = { path = "../../extern/rust/rustc/src/libcore" }
common = { path = "../common" }
hil = { path = "../hil" }
main = { path = "../main" }
