[package]
name = "nrf51822"
version = "0.1.0"
authors = ["Amit Levy <amit@amitlevy.com>"]

build = "build.rs"

[dependencies]
core = { path = "../../../extern/rust/rustc/src/libcore" }
common = { path = "../../common" }
cortexm0 = { path = "../../arch/cortex-m0" }
hil = { path = "../../hil" }
main = { path = "../../main" }

[build-dependencies]
gcc = "0.3"
