[package]
name = "storm"
version = "0.1.0"
authors = ["Amit Levy <amit@amitlevy.com>"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
core = { path = "../../../extern/rust/rustc/src/libcore" }
common = { path = "../../common" }
cortexm4 = { path = "../../arch/cortex-m4" }
drivers = { path = "../../drivers" }
hil = { path = "../../hil" }
main = { path = "../../main" }
sam4l = { path = "../../chips/sam4l" }
support = { path = "../../support" }
